title = Franco Magic Mod
name = francomagicmod
description = "Un mod de magie pour core, ajoutant des sorts, des potions et des artefacts magiques."
author = Calice
depends = default, playereffects, mana, entity_modifier
optional_depends = mobs_animal, forgotten_monsters